export const AVATAR_CLEAN_STATE = 'AVATAR_CLEAN_STATE';
export const AVATAR_SET_ERROR = 'AVATAR_SET_ERROR';
export const AVATAR_RESET_ERROR = 'AVATAR_RESET_ERROR';

export const AVATAR_UPLOAD = 'AVATAR_UPLOAD';
export const AVATAR_UPLOAD_SUCCESS = 'AVATAR_UPLOAD_SUCCESS';
export const AVATAR_UPLOAD_FAILURE = 'AVATAR_UPLOAD_FAILURE';
export const AVATAR_UPLOAD_PROGRESS = 'AVATAR_UPLOAD_PROGRESS';

export const AVATAR_SET = 'AVATAR_SET';
export const AVATAR_SET_SUCCESS = 'AVATAR_SET_SUCCESS';
export const AVATAR_SET_FAILURE = 'AVATAR_SET_FAILURE';

export const AVATAR_REMOVE = 'AVATAR_REMOVE';
export const AVATAR_REMOVE_SUCCESS = 'AVATAR_REMOVE_SUCCESS';
export const AVATAR_REMOVE_FAILURE = 'AVATAR_REMOVE_FAILURE';
